#### Inference API

In [ ]:
repo = "sshleifer/distilbart-cnn-12-6"
api_token = "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"
inference = InferenceApi(repo_id=repo, token=api_token, task="summarization")

In [ ]:
inputs = "Johannes Gutenberg (1398 – 1468) was a German goldsmith and publisher who introduced printing to Europe. His introduction of mechanical movable type printing to Europe started the Printing Revolution and is widely regarded as the most important event of the modern period. It played a key role in the scientific revolution and laid the basis for the modern knowledge-based economy and the spread of learning to the masses. Gutenberg many contributions to printing are: the invention of a process for mass-producing movable type, the use of oil-based ink for printing books, adjustable molds, and the use of a wooden printing press. His truly epochal invention was the combination of these elements into a practical system that allowed the mass production of printed books and was economically viable for printers and readers alike. In Renaissance Europe, the arrival of mechanical movable type printing introduced the era of mass communication which permanently altered the structure of society. The relatively unrestricted circulation of information—including revolutionary ideas—transcended borders, and captured the masses in the Reformation. The sharp increase in literacy broke the monopoly of the literate elite on education and learning and bolstered the emerging middle class."
params = {"num_beams": 5, "length_penalty": 2.0, "no_repeat_ngram_size": 3}

In [ ]:
inference(inputs, params)

[{'summary_text': ' Johannes Gutenberg (1398 – 1468) was a German goldsmith and publisher . His introduction of mechanical movable type printing to Europe started the Printing Revolution and is widely regarded as the most important event of the modern period . It played a key role in the scientific revolution and laid the basis for the modern knowledge-based economy and the spread of learning to the masses .'}]

In [ ]:
import pandas as pd

path = 'data/'

raw_text = pd.read_csv(path + "news_summary_more.csv", encoding='iso-8859-1')
summary = pd.read_csv(path + "news_summary.csv", encoding='iso-8859-1')

# cnn_text = pd.read_csv(path + "cnn_news.csv", encoding='iso-8859-1')

In [ ]:
def summarize(text, num_beams=4, length_penalty=1.0, max_length=50, min_length=10, no_repeat_ngram_size=3):
  
  text = text.replace('\n','')
  text_input_ids = tokenizer.batch_encode_plus([text], return_tensors='pt')['input_ids'].to('cpu')

  summary_ids = model.generate(text_input_ids, num_beams=int(num_beams),
  length_penalty=float(length_penalty), 
  max_length=int(max_length),
  min_length=int(min_length), 
  no_repeat_ngram_size=int(no_repeat_ngram_size),
  top_k=50)

  summary_txt = tokenizer.decode(summary_ids.squeeze(), skip_special_tokens=True)
  return summary_txt

In [ ]:
text = """
Johannes Gutenberg (1398 – 1468) was a German goldsmith and publisher who introduced printing to Europe. His introduction of mechanical movable type printing to Europe started the Printing Revolution and is widely regarded as the most important event of the modern period. It played a key role in the scientific revolution and laid the basis for the modern knowledge-based economy and the spread of learning to the masses.

Gutenberg many contributions to printing are: the invention of a process for mass-producing movable type, the use of oil-based ink for printing books, adjustable molds, and the use of a wooden printing press. His truly epochal invention was the combination of these elements into a practical system that allowed the mass production of printed books and was economically viable for printers and readers alike.

In Renaissance Europe, the arrival of mechanical movable type printing introduced the era of mass communication which permanently altered the structure of society. The relatively unrestricted circulation of information—including revolutionary ideas—transcended borders, and captured the masses in the Reformation. The sharp increase in literacy broke the monopoly of the literate elite on education and learning and bolstered the emerging middle class.
"""

Johannes Gutenberg (1398 – 1468) was a German goldsmith and publisher who introduced printing to Europe. His introduction of mechanical movable type printing to Europe started the Printing Revolution and is widely regarded as the most important event of the modern period. It played a key role in the scientific revolution and laid the basis for the modern knowledge-based economy and the spread of learning to the masses.

Gutenberg many contributions to printing are: the invention of a process for mass-producing movable type, the use of oil-based ink for printing books, adjustable molds, and the use of a wooden printing press. His truly epochal invention was the combination of these elements into a practical system that allowed the mass production of printed books and was economically viable for printers and readers alike.

In Renaissance Europe, the arrival of mechanical movable type printing introduced the era of mass communication which permanently altered the structure of society. The relatively unrestricted circulation of information—including revolutionary ideas—transcended borders, and captured the masses in the Reformation. The sharp increase in literacy broke the monopoly of the literate elite on education and learning and bolstered the emerging middle class.

In [ ]:
summarize(text, 4, 1.0, 50, 20, 4)

' Gutenberg was one of the founding fathers of the printing revolution in the 14th Century. and his work was credited with the invention of the printing system.'

### **Fine-tuned BART model**

#### **Setup**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!pip install datasets
!pip install transformers
!pip install rouge_score
!pip install sentencepiece

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 362 kB 5.2 MB/s 
     |████████████████████████████████| 212 kB 66.8 MB/s 
     |████████████████████████████████| 1.1 MB 54.7 MB/s 
     |████████████████████████████████| 101 kB 12.6 MB/s 
     |████████████████████████████████| 140 kB 73.1 MB/s 
     |████████████████████████████████| 596 kB 64.5 MB/s 
     |████████████████████████████████| 127 kB 73.7 MB/s 
     |████████████████████████████████| 94 kB 3.8 MB/s 
     |████████████████████████████████| 144 kB 71.1 MB/s 
     |████████████████████████████████| 271 kB 71.3 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
ERROR: pip's dep

In [3]:
import os
import numpy as np
import torch
import datasets
from transformers import (
    AutoModelForSeq2SeqLM,
    AutoTokenizer,
    Seq2SeqTrainingArguments, 
    Seq2SeqTrainer,
    DataCollatorForSeq2Seq
)
import nltk

os.environ['CUDA_LAUNCH_BLOCKING'] = "1"

#### **Model and Tokenizer**

In [4]:
model_name = "sshleifer/distilbart-cnn-12-6"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

encoder_max_len = 512
decoder_max_len = 64

Downloading:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.76k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/878k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.14G [00:00<?, ?B/s]

In [8]:
# Check the vocabulary size of tokenizer and model whether they are matching
mismatch = False

print(f"Tokenizer: {tokenizer.vocab_size}")
print(f"Model: {model.config.vocab_size}")

if len(tokenizer) != model.config.vocab_size:
    mismatch = True

Tokenizer: 50265
Model: 50264


In [9]:
if (mismatch):
    model.resize_token_embeddings(len(tokenizer))
    print(f"Tokenizer: {tokenizer.vocab_size}")
    print(f"Model: {model.config.vocab_size}")

Tokenizer: 50265
Model: 50265


#### **Data preparation**
**Read data**

In [ ]:
# # Use local dataset
# src = "drive/MyDrive/Personal Workspace/Colab Notebooks/NLP/data_sm.jsonl"
# data = datasets.load_dataset("json", data_files=src)

# train_val_test = data["train"].train_test_split(shuffle=True, seed=42, test_size=0.1)

# dataset = datasets.DatasetDict({
#     "train": train_val_test["train"], # Train
#     "val": train_val_test["test"], # Validation
# })

In [11]:
# Download dataset
language = "english"

data = datasets.load_dataset("wiki_lingua", name=language, split="train[:10000]")

Generating train split:   0%|          | 0/57945 [00:00<?, ? examples/s]

Dataset wiki_lingua downloaded and prepared to /root/.cache/huggingface/datasets/wiki_lingua/english/1.1.1/dad5f0710d1bb1a2ed1eb7633802fe147ebd27a3812985f5641bb7aca6ba5c08. Subsequent calls will reuse this data.


**Preprocessing and Split**

In [12]:
def flatten(dataset):
    return {
        "document": dataset["article"]["document"],
        "summary": dataset["article"]["summary"],
    }


def list2samples(dataset):
    documents = []
    summaries = []
    for sample in zip(dataset["document"], dataset["summary"]):
        if len(sample[0]) > 0:
            documents += sample[0]
            summaries += sample[1]
    return {"document": documents, "summary": summaries}


dataset = data.map(flatten, remove_columns=["article", "url"])
dataset = dataset.map(list2samples, batched=True)

train_data, validation_data = dataset.train_test_split(test_size=0.2).values()

Parameter 'function'=<function flatten at 0x7fdb6e6d5320> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.


  0%|          | 0/57945 [00:00<?, ?ex/s]

  0%|          | 0/58 [00:00<?, ?ba/s]

**Tokenize data**

In [13]:
def batch_tokenizing(batch, tokenizer, max_input_len, max_output_len):
    input_, output_ = batch["document"], batch["summary"]
    input_tokenized = tokenizer(
        input_, padding="max_length", max_length=max_input_len, truncation=True
    )
    output_tokenized = tokenizer(
        output_, padding="max_length", max_length=max_output_len, truncation=True
    )

    batch = {key: value for key, value in input_tokenized.items()}

    batch["labels"] =[[-100 if token == tokenizer.pad_token_id else token for token in l]
                        for l in output_tokenized["input_ids"]]

    return batch

train_data = train_data.map(
    lambda batch: batch_tokenizing(
        batch, tokenizer, encoder_max_len, decoder_max_len
    ),
    batched=True,
    remove_columns=train_data.column_names,
)

val_data = validation_data.map(
    lambda batch: batch_tokenizing(
        batch, tokenizer, encoder_max_len, decoder_max_len
    ),
    batched=True,
    remove_columns=validation_data.column_names,
)

  0%|          | 0/114 [00:00<?, ?ba/s]

  0%|          | 0/29 [00:00<?, ?ba/s]

#### **Training model**

**Metrics**

In [14]:
nltk.download("punkt", quiet=True)

metric = datasets.load_metric("rouge")

def postprocess_data(preds, labels):
    preds = [pred.strip() for pred in preds]
    labels = [label.strip() for label in labels]

    # Join sequences with newline between them for rougle calculation
    preds = ["\n".join(nltk.sent_tokenize(pred)) for pred in preds]
    labels = ["\n".join(nltk.sent_tokenize(label)) for label in labels]

    return preds, labels

def calculate_metric(eval_result):
    preds, labels = eval_result
    if isinstance(preds, tuple):
        preds = preds[0]
    
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    # Preprocess prediction and label for metric computation
    decoded_preds, decoded_labels = postprocess_data(decoded_preds, decoded_labels)

    result = metric.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
    result = {key: value.mid.fmeasure * 100 for key, value in result.items()}

    pred_len = [np.count_nonzero(pred != tokenizer.pad_token_id) for pred in preds]
    result["res_"] = np.mean(pred_len)
    result = {key: round(val, 4) for key, val in result.item()}

    return result

**Training arguments**

In [15]:
from huggingface_hub import notebook_login

notebook_login()

Login successful
Your token has been saved to /root/.huggingface/token
Authenticated through git-credential store but this isn't the helper defined on your machine.
You might have to re-authenticate when pushing to the Hugging Face Hub. Run the following command in your terminal in case you want to set this credential helper as the default

git config --global credential.helper store


In [16]:
train_args = Seq2SeqTrainingArguments(
    output_dir="distilbart-ftn-wiki_lingua",
    num_train_epochs=1,
    do_train=True,
    do_eval=True,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    warmup_steps=420,
    weight_decay=0.1,
    label_smoothing_factor=0.1,
    predict_with_generate=True,
    logging_dir="logs",
    logging_steps=50,
    save_total_limit=3,
    push_to_hub=True
)

data_colla = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)

trainer = Seq2SeqTrainer(
    model=model,
    args=train_args,
    data_collator=data_colla,
    train_dataset=train_data,
    eval_dataset=val_data,
    tokenizer=tokenizer,
    compute_metrics=calculate_metric,
)

Cloning https://huggingface.co/datien228/distilbart-ftn-wiki_lingua into local empty directory.


**Evalute model before training**

In [17]:
trainer.evaluate()

***** Running Evaluation *****
  Num examples = 28292
  Batch size = 4


KeyboardInterrupt: ignored

**Train model (fine-tune)**

In [ ]:
trainer.train()

**Evalute model after training**

In [ ]:
trainer.evaluate()

#### **Evaluate and comparison**

Compare the summaries from the fine-tuned BART model and the original BART model

In [ ]:
def generate_summary(samples, model):
    inputs = tokenizer(
        samples["document"],
        padding="max_length",
        truncation=True,
        max_length=encoder_max_len,
        return_tensors="pt",
    )
    input_ids = inputs.input_ids.to(model.device)
    attention_mask = inputs.attention_mask.to(model.device)
    outputs = model.generate(input_ids, attention_mask=attention_mask)
    output_str = tokenizer.batch_decode(outputs, skip_special_tokens=True)

    return outputs, output_str

original_model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

sample_test = val_data.select(range(15))

summary_before = generate_summary(sample_test, original_model)[1]
summary_after = generate_summary(sample_test, model)[1]

In [ ]:
import tabulate

In [ ]:
print("\nSource document:\n")
print(tabulate(list(enumerate(sample_test["document"])), headers=["ID", "Document"]))

print("\Target summary:\n")
print(tabulate(list(enumerate(sample_test["summary"])), headers=["ID", "Target summary"]))

print("\Target summary:\n")
print(tabulate(
        zip(
            range(len(summary_after)),
            summary_after,
            summary_before,
        ),
        headers=["ID", "Summary before", "Summary after"]
    )
)